jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: mvn test
      - store_test_results:
          path: target/surefire-reports
      - codecov/upload:
          file: target/surefire-reports/TEST-com.dunzo.coffeemachine.CoffeemachineApplicationTests.xml
