version: 2.1
orbs:
  codecov: codecov/codecov@3.1.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: mvn test
      - store_test_results:
          path: target/surefire-
      - codecov/upload