version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    steps:
      - codecov/upload:
          file: {{ target/surefire-reports/TEST-com.dunzo.coffeemachine.CoffeemachineApplicationTests.xml }}
